[features]
seeds = false
[programs.devnet]
cbs_protocol = "KJavsL5joNr5dAkkgdqsnmnoWDkvwssihnXkjnQJhBf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/coredev0927/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
